### ISSUE TITLE
Add MEBx password requirements

### ISSUE THREAD

**Issue by cornuwel** [fitbeard/home-lab#6]
This one threw me for a loop. The default password might be 'admin', but the new password must respect:
1 AT LEAST 8 CHARACTERS
2 ONE SPECIAL CHARACTER
3 ONE NUMBER
4 ONE CAPITAL LETTER
5 ONE SMALL LETTER

**Comment by fitbeard** [comment]
https://github.com/fitbeard/home-lab/blob/master/intel-amt-kvm/intel-amt-kvm.sh#L12

**Comment by fitbeard** [comment]
You're right. Should be written in the README, not in a script comment.
